<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PC324048" name="com.pulselms.app.test.LoginTestAndroid" tests="8" failures="1" timestamp="7 Oct 2015 09:38:00 GMT" time="193.402" errors="1">
  <testcase name="TC004_SigninVerificationOfErrorMessageForInvalidPassword" time="24.133" classname="com.pulselms.app.test.LoginTestAndroid"/>
  <testcase name="TC017_SigninVerfiyingApplicationAfterDeviceIsLocked" time="26.542" classname="com.pulselms.app.test.LoginTestAndroid">
    <error type="com.pulselms.app.framework.BrowserBotException" message="Invalid element locator parameter -ram@example.com">
      <![CDATA[com.pulselms.app.framework.BrowserBotException: Invalid element locator parameter -ram@example.com
	at com.pulselms.app.framework.ObjectLocators.getBySelector(ObjectLocators.java:129)
	at com.pulselms.app.framework.WebDriverBase.isElementPresent(WebDriverBase.java:626)
	at com.pulselms.app.screen.LoginScreenAndroid.isEmailTextPresent(LoginScreenAndroid.java:93)
	at com.pulselms.app.test.LoginTestAndroid.TC017_SigninVerfiyingApplicationAfterDeviceIsLocked(LoginTestAndroid.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:648)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:834)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1142)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1176)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1101)
	at org.testng.TestNG.run(TestNG.java:1009)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- TC017_SigninVerfiyingApplicationAfterDeviceIsLocked -->
  <testcase name="TC007_SigninVerificationOfErrorMessageIfUserNameIsBlank" time="20.971" classname="com.pulselms.app.test.LoginTestAndroid"/>
  <testcase name="TC006_SigninVerificationOfErrorMessageForBothFieldsBlank" time="21.076" classname="com.pulselms.app.test.LoginTestAndroid">
    <failure type="java.lang.AssertionError" message="expected [Please enter your email address/user name. Please enter your password.] but found [Please enter your email address/user name.]">
      <![CDATA[java.lang.AssertionError: expected [Please enter your email address/user name. Please enter your password.] but found [Please enter your email address/user name.]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at com.pulselms.app.test.LoginTestAndroid.TC006_SigninVerificationOfErrorMessageForBothFieldsBlank(LoginTestAndroid.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:648)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:834)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1142)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1176)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1101)
	at org.testng.TestNG.run(TestNG.java:1009)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- TC006_SigninVerificationOfErrorMessageForBothFieldsBlank -->
  <testcase name="TC016_SigninVerfiyingBehaviorOfApplicationAfterOrientationChange" time="25.124" classname="com.pulselms.app.test.LoginTestAndroid"/>
  <testcase name="TC003_SigninVerificationOfErrorMessageForInvalidEmailId" time="24.618" classname="com.pulselms.app.test.LoginTestAndroid"/>
  <testcase name="TC001_SigninVerificationOfSuccessfulLogin" time="28.170" classname="com.pulselms.app.test.LoginTestAndroid"/>
  <testcase name="TC008_SigninVerificationOfErrorMessageIfPasswordIsBlank" time="22.768" classname="com.pulselms.app.test.LoginTestAndroid"/>
</testsuite> <!-- com.pulselms.app.test.LoginTestAndroid -->
